server:
    port: 8089

log:
    level: DEBUG
    appender: stash
    home:
    stash:
        addresses: node01.public.logstash.test:9999,node02.public.logstash.test:9999

consul:
    host: 192.168.1.24
    port: 8500
    acl-token: '8970be09-01e7-ba07-349e-f897adebf589'

basic:
    version: 2.0
    env: test
    pdf_url_prefix: https://ydannouncementbucket.obs.cn-north-1.myhuaweicloud.com/
    is_ocr: true
    is_immediate_ocr: false
    complete_display: false
    parse_stream_table: true
    formula_recognize: false

# pulsar监听
pulsar:
    servers: pulsar://172.16.20.97:6650,172.16.20.98:6650,172.16.20.99:6650
    token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwdWxzYXItdXNlciJ9.JKJIHQiiuVyv9TnsFQCLhobUUnycOvehU0bGe3gr5xA
    receive_topic_name: capital/pdf_parse/announcement_parse_increment
    send_topic_name: capital/pdf_parse/announcement_increment_parse_result
    count: 3
    ocr_send_topic_name: capital/pdf_parse/announcement_ocr_image_analysis_increment
    ocr_receive_topic_name: capital/pdf_parse/announcement_ocr_image_analysis_increment_result
    ocrCount: 2

oss:
    temp_bucket_name: stock-temp-bucket
    permanent_bucket_name: announcement-pdf-bucket
    endpoint: https://obs.cn-north-1.myhuaweicloud.com
    access_key: EUD3T68PPED8VI2ZHX2K
    secret_key: qOe8kcPGpJk0ZTIo1baWqQubShQoiyfOZThbp5dE
    domain_name: https://announcement-pdf-bucket.obs.cn-north-1.myhuaweicloud.com/

paddle:
    url: http://192.168.1.193:8088/layout-parsing

pdf:
    temp:
        path: /tmp/pdf_parse
    output:
        path: /tmp/pdf_parse/output
