server:
    servlet:
        context-path: /

spring:
  application:
    name: opendataloader-pdf-server
  profiles:
      active: dev
  main:
      allow-bean-definition-overriding: true
  cloud:
      consul:
          host: ${consul.host}
          port: ${consul.port}
          discovery:
              prefer-ip-address: true
              acl-token: ${consul.acl-token}
              instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
              health-check-path: /health
          config:
              enabled: true   # 开启Consul配置中心
              format: YAML    # 表示consul上面文件的格式 有四种 YAML PROPERTIES KEY-VALUE FILES
              data-key: data    #表示consul上面的KEY值(或者说文件的名字) 默认是data
              prefix: config/capital # 设置配置值的基本文件夹
              #        defaultContext: service-sample
              profileSeparator: ','
              watch:
                  enabled: true
              acl-token: ${consul.acl-token}

logging:
  level:
    org.opendataloader.pdf.server: DEBUG

http:
    rest-template:
        request-timeout: 60000
        connect-timeout: 60000
        read-timeout: 60000

